In [1]:
import pandas as pd
import numpy as np
import statsmodels.api as sm
from statsmodels.formula.api import ols
import glob
from matplotlib import pyplot as plt
from pathlib import Path
import statistics
import scipy
from ipynb.fs.full.taylorDiagram import TaylorDiagram

In [2]:
df=pd.read_csv("/home/nishu/my_projects/NMP/22_08_22/GPCC_daily_for_validation/KR_yearly.csv")

In [3]:
df

    Year         ppt   ppanmly
0   1982  411.586208  0.628757
1   1983  397.056725  0.416778
2   1984  314.364366 -0.789670
3   1985  247.626339 -1.763350
4   1986  381.209363  0.185572
5   1987  359.443561 -0.131983
6   1988  410.895604  0.618682
7   1989  309.608440 -0.859057
8   1990  402.975206  0.503126
9   1991  336.956603 -0.460058
10  1992  517.770794  2.177947
11  1993  328.031055 -0.590278
12  1994  355.727720 -0.186195
13  1995  424.463967  0.816639
14  1996  494.084577  1.832375
15  1997  405.056526  0.533492
16  1998  389.357967  0.304456
17  1999  357.725502 -0.157048
18  2000  255.913005 -1.642451
19  2001  227.077562 -2.063149
20  2002  298.252085 -1.024741
21  2003  454.009584  1.247697
22  2004  352.040185 -0.239995
23  2005  407.893706  0.574885
24  2006  421.948813  0.779943
25  2007  293.111081 -1.099746
26  2008  389.303459  0.303661
27  2009  259.309333 -1.592900
28  2010  457.060885  1.292214
29  2011  333.959853 -0.503780
30  2012  332.190770 -0.529590
31  2013  384.287106  0.230475
32  2014  387.397603  0.275855
33  2015  497.662695  1.884578
34  2016  269.444072 -1.445038
35  2017  365.772562 -0.039645
36  2018  326.429976 -0.613637
37  2019  408.217491  0.579609
38  2020  412.610529  0.643702
39  2021  361.763808 -0.098131

In [4]:
print(statistics.stdev(df["ppanmly"]))

1.0000000000000002

In [5]:
tlrfrm=df.drop(df.index[21:40],0)
print(tlrfrm)

    Year         ppt   ppanmly
0   1982  411.586208  0.628757
1   1983  397.056725  0.416778
2   1984  314.364366 -0.789670
3   1985  247.626339 -1.763350
4   1986  381.209363  0.185572
5   1987  359.443561 -0.131983
6   1988  410.895604  0.618682
7   1989  309.608440 -0.859057
8   1990  402.975206  0.503126
9   1991  336.956603 -0.460058
10  1992  517.770794  2.177947
11  1993  328.031055 -0.590278
12  1994  355.727720 -0.186195
13  1995  424.463967  0.816639
14  1996  494.084577  1.832375
15  1997  405.056526  0.533492
16  1998  389.357967  0.304456
17  1999  357.725502 -0.157048
18  2000  255.913005 -1.642451
19  2001  227.077562 -2.063149
20  2002  298.252085 -1.024741

In [6]:
folder ='/home/nishu/my_projects/NMP/22_08_22/Future_Projection_Himlaya_2_8_2022/rawdata_182993KR45/monthly_dump0_1986_2005'

corr=np.zeros(43)
stddev=np.zeros(43)
models=[]
c=0
for file in Path(folder).glob('*.txt'):
    df1 = pd.read_csv(file)
    df1=df1.drop(df1.index[153:156],0)
    df1=df1.drop(df1.index[0:132],0)
#     print(df1)
    res=scipy.stats.pearsonr(tlrfrm["ppanmly"],df1["ppanmly"])
    corr[c]=res[0]
    stddev[c]=scipy.stats.tstd(df1["ppanmly"])
    c+=1
    mname=str(file)
#     print(len(mname))
    mname=mname[114:len(mname)-53]
#     print(type(mname))
    models.append(mname)
#     print(mname)
# print("corr",corr)
# print("stddev",stddev)
print(models)
tlr=pd.DataFrame()
tlr["Mname"]=models
tlr["corr"]=corr
tlr["stddev"]=stddev
print(tlr)

['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '']
   Mname      corr    stddev
0         0.065463  0.327499
1         0.136861  0.462601
2        -0.179910  0.606573
3        -0.248062  0.334990
4         0.355042  0.356542
5        -0.101467  0.521375
6        -0.033387  0.597820
7         0.229426  0.483087
8        -0.210350  0.433099
9         0.373748  0.397256
10       -0.197880  0.359090
11       -0.208647  0.352475
12       -0.292999  0.365544
13       -0.274330  0.576736
14       -0.054992  0.488497
15       -0.063704  0.752991
16       -0.150229  0.366199
17       -0.066502  0.369935
18       -0.151753  0.449677
19        0.010078  0.376080
20       -0.069239  0.385494
21       -0.032892  0.228533
22        0.543868  0.384782
23        0.434529  0.294171
24       -0.227044  0.339483
25       -0.053127  0.303960
26        0.038205  0.288497
27       -0.055900  0.270519
28        0.408081  0.381401
29        0.291288  0.292244
30       -0.016201  0.306496
31       -0.080414  0.308954
32       -0.328609  0.303648
33        0.116801  0.462613
34       -0.042859  0.305072
35       -0.242125  0.887152
36        0.421397  0.902724
37        0.484324  0.260892
38        0.054935  0.482874
39        0.067662  0.423121
40       -0.117532  0.703061
41       -0.379834  0.747636
42       -0.039640  0.067586